server.port=${PORT}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

api.url=${FACTUS_ENDPOINT_SANDBOX}
api.user=${FACTUS_USER}
api.password=${FACTUS_PASSWORD}
api.client_id=${FACTUS_CLIENT_ID}
api.client_secret=${FACTUS_CLIENT_SECRET}

logging.level.root=INFO
logging.level.com.factusimple=DEBUG