spring.profiles.active=dev

spring.application.name=factusimple-api

server.servlet.context-path=/api

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect